version: 2.1
jobs:
  print_hello:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - run:
          name: Print Hello
          command: |
            echo "Hello"
  print_world:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - run: 
          name: Print world
          command: |
            echo "World"
            echo "My pipeline id is << pipeline.id >> and my git branch is << pipeline.git.branch >>."
            echo "My github url is << pipeline.project.git_url >> and git tools is << pipeline.project.type >>"
  print_my_name:
    environment:
      NAME: Oguazu Stanley
    docker:
      - image: circleci/node:13.8.0
    steps:
      - run:
          name: Print my name
          command: |
            echo "My name is << name >> and it's nice to meet you"
workflows:
  welcome:
    jobs:
      - print_hello
      - print_world:
          requires: [print_hello]
      - print_my_name