version: 2.1
jobs:
  print_hello:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - run:
          name: Print Hello
          command: |
            echo "Hello"
  print_world:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - run: 
          name: Print world
          command: |
            echo "World"
            echo "My pipeline id is << pipeline.id >> and my git branch is << pipeline.git.branch >>."
workflows:
  welcome:
    jobs:
      - print_hello
      - print_world:
          requires: [print_hello]