version: 2.1
commands:
  greeting:
    description: "just testing reusable code"
    parameters:
      to:
        type: string
        default: "Some one"
    steps:
      - run: echo "Hello << parameters.to >>"
jobs:
  say_hello_world_output:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - run: echo "Hello World" > ~/output.txt
      - persist_to_workspace:
          root: ~/
          paths:
            - output.txt
  print_output_file:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - attach_workspace:
          at: ~/
      - run: cat ~/output.txt
  print_world:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - greeting:
          to: "Grey white"
      - run: 
          name: Print world
          command: |
            echo "World"
            echo "My pipeline id is << pipeline.id >> and my git branch is << pipeline.git.branch >>."
            echo "My github url is << pipeline.project.git_url >> and git tools is << pipeline.project.type >>"
  print_my_name:
    environment:
      NAME: Oguazu Stanley
    docker:
      - image: circleci/node:13.8.0
    steps:
      - run:
          name: Print my name
          command: |
            echo "My name is ${NAME} and it's nice to meet you"
  test_when_on_fail:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - run: exit 1
      - run: 
          name: run on error
          command: |
            echo "Test failed"
          when: on_fail
            
workflows:
  welcome:
    jobs:
      - say_hello_world_output
      - print_output_file:
          requires:
            - say_hello_world_output
      - print_world
      - print_my_name:
          requires: [print_world]
      - test_when_on_fail